# This docker-compose is for local development / test only

version: '3.6'

services:
  # Server
  server:
    image: docker.pkg.github.com/landazuripaul/rueda-sabor/rueda-sabor-server:latest
    volumes:
      - ./packages/server/env/.env.local:/usr/src/rueda-sabor/packages/server/env/.env.local
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=local

  # Client
  client:
    image: docker.pkg.github.com/landazuripaul/rueda-sabor/rueda-sabor-client:latest
    ports:
      - '8000:80'
